name: cic
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - scikit-image
  - ffmpeg
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pre-commit
  - pip:
    - protobuf==3.20.*
    - termcolor==1.1.0
    - dm_control
    - tensorboard
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - opencv-python==4.5.3.56
    - wandb==0.13.2
    - git+https://github.com/Zulko/moviepy.git
